In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("googleplaystore.csv")

In [9]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [11]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [12]:
df.shape

(10841, 13)

In [13]:
df.isna().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [14]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [15]:
df.duplicated().sum()

483

In [16]:
df.shape

(10841, 13)

# Drop App Feature
df.drop("App",axis=1,inplace=True)

# Drop Duplicate Item

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.shape

(10358, 13)

In [19]:
df.duplicated().sum()

0

In [20]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# #Category Feature

In [21]:
df["Category"].value_counts()

FAMILY                 1943
GAME                   1121
TOOLS                   843
BUSINESS                427
MEDICAL                 408
PRODUCTIVITY            407
PERSONALIZATION         388
LIFESTYLE               373
COMMUNICATION           366
FINANCE                 360
SPORTS                  351
PHOTOGRAPHY             322
HEALTH_AND_FITNESS      306
SOCIAL                  280
NEWS_AND_MAGAZINES      264
TRAVEL_AND_LOCAL        237
BOOKS_AND_REFERENCE     230
SHOPPING                224
DATING                  196
VIDEO_PLAYERS           175
MAPS_AND_NAVIGATION     137
EDUCATION               130
FOOD_AND_DRINK          124
ENTERTAINMENT           111
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
HOUSE_AND_HOME           80
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: Category, dtype: int64

In [22]:
df["Category"].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [23]:
df[df["Category"]=='1.9']
df.reset_index()

,index,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10353,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10354,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10355,10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10356,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10357,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [24]:
df.reset_index()
df.loc[10470:10473]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10470,Jazz Wi-Fi,COMMUNICATION,3.4,49,4.0M,"10,000+",Free,0,Everyone,Communication,"February 10, 2017",0.1,2.3 and up
10471,Xposed Wi-Fi-Pwd,PERSONALIZATION,3.5,1042,404k,"100,000+",Free,0,Everyone,Personalization,"August 5, 2014",3.0.0,4.0.3 and up
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN
10473,osmino Wi-Fi: free WiFi,TOOLS,4.2,134203,4.1M,"10,000,000+",Free,0,Everyone,Tools,"August 7, 2018",6.06.14,4.4 and up

In [25]:
sorted(df["Category"].unique())

['1.9',
 'ART_AND_DESIGN',
 'AUTO_AND_VEHICLES',
 'BEAUTY',
 'BOOKS_AND_REFERENCE',
 'BUSINESS',
 'COMICS',
 'COMMUNICATION',
 'DATING',
 'EDUCATION',
 'ENTERTAINMENT',
 'EVENTS',
 'FAMILY',
 'FINANCE',
 'FOOD_AND_DRINK',
 'GAME',
 'HEALTH_AND_FITNESS',
 'HOUSE_AND_HOME',
 'LIBRARIES_AND_DEMO',
 'LIFESTYLE',
 'MAPS_AND_NAVIGATION',
 'MEDICAL',
 'NEWS_AND_MAGAZINES',
 'PARENTING',
 'PERSONALIZATION',
 'PHOTOGRAPHY',
 'PRODUCTIVITY',
 'SHOPPING',
 'SOCIAL',
 'SPORTS',
 'TOOLS',
 'TRAVEL_AND_LOCAL',
 'VIDEO_PLAYERS',
 'WEATHER']

In [26]:
!pip install sklearn

Requirement already satisfied: sklearn in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from sklearn) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (1.8.0)
Requirement already satisfied: joblib>=0.11 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: numpy>=1.14.6 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (1.22.3)

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
lb = LabelEncoder()

In [29]:
df["Category"] = lb.fit_transform(df["Category"])

In [30]:
sorted(df["Category"].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33]

In [31]:
df.isna().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [32]:
df["Rating"].value_counts()

4.4     1032
4.3     1016
4.5      977
4.2      888
4.6      768
4.1      657
4.0      539
4.7      484
3.9      372
3.8      293
5.0      271
3.7      231
4.8      228
3.6      169
3.5      157
3.4      127
3.3      101
4.9       87
3.0       82
3.1       69
3.2       64
2.9       45
2.8       40
2.6       24
2.7       23
2.5       20
2.3       20
2.4       19
1.0       16
2.2       14
1.9       12
2.0       12
1.7        8
1.8        8
2.1        8
1.6        4
1.4        3
1.5        3
1.2        1
19.0       1
Name: Rating, dtype: int64

In [33]:
df["Rating"].fillna(df["Rating"].mean(),inplace=True)

In [34]:
df["Rating"].isna().sum()

0

In [35]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,1,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,1,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",1,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,1,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,1,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,12,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,12,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,21,4.189542,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,4,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,19,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [36]:
df["Rating"].mean()

4.18954233666929

In [37]:
df["Rating"].median()

4.2

In [38]:
df[df["Size"].str.strip().str[-1] == '+']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,0,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [39]:
df["Size"].value_counts()

Varies with device    1526
11M                    188
12M                    186
13M                    186
14M                    182
                      ...
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: Size, Length: 462, dtype: int64

In [40]:
df.at[10472,"Size"] = "11M"

In [41]:
df["Size"].str.strip().str[-1].unique()

array(['M', 'e', 'k'], dtype=object)

In [42]:
df[df["Size"].str.strip().str[-1] == 'e']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
37,Floor Plan Creator,1,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up
42,Textgram - write on photos,1,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device
52,Used Cars and Trucks for Sale,2,4.6,17057,Varies with device,"1,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device
67,Ulysse Speedometer,2,4.3,40211,Varies with device,"5,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device
68,REPUVE,2,3.9,356,Varies with device,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10713,My Earthquake Alerts - US & Worldwide Earthquakes,33,4.4,3471,Varies with device,"100,000+",Free,0,Everyone,Weather,"July 24, 2018",Varies with device,Varies with device
10725,Posta App,20,3.6,8,Varies with device,"1,000+",Free,0,Everyone,Maps & Navigation,"September 27, 2017",Varies with device,4.4 and up
10765,Chat For Strangers - Video Chat,28,3.4,622,Varies with device,"100,000+",Free,0,Mature 17+,Social,"May 23, 2018",Varies with device,Varies with device
10826,Frim: get new friends on local chat rooms,28,4.0,88486,Varies with device,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device
10839,The SCP Foundation DB fr nn5n,4,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device

In [43]:
df.drop(columns = "App")

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,1,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,1,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,1,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,1,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,12,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,12,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,21,4.189542,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,4,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,19,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [44]:
df["Installs"] = df["Installs"].apply(lambda x : x.replace("+","") if x[-1] == "+" else x)

In [45]:
df["Installs"] = df["Installs"].apply(lambda x : x.replace(",",""))

In [46]:
df["Installs"].head(5)

0       10000
1      500000
2     5000000
3    50000000
4      100000
Name: Installs, dtype: object

In [47]:
df.drop("App",axis=1,inplace=True)

In [48]:
df.dtypes

Category            int32
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

# #Reviews feature

In [49]:
#convert Reviews (Object to float)

In [50]:
#find Invalid data
df[df['Rating'] > 5]

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,0,19.0,3.0M,11M,Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [51]:
#Delete Invalid data
df = df.drop(10472)

In [52]:
#Convert Object to integer
df['Reviews'] = df['Reviews'].astype(int, errors = 'raise')

# Installs feature

In [53]:
#Convert Object to integer
df['Installs'] = df['Installs'].astype(int, errors = 'raise')

# Price feature

In [54]:
#Remove $ from the Price feature
df["Price"] = df["Price"].apply(lambda x : x.replace("$",""))

In [55]:
#Convert Object to float
df['Price'] = df['Price'].astype(float, errors = 'raise')

In [56]:
df['Price'].value_counts()

0.00      9592
0.99       146
2.99       125
1.99        73
4.99        70
          ...
389.99       1
19.90        1
1.75         1
14.00        1
1.04         1
Name: Price, Length: 92, dtype: int64

In [57]:
df["Content Rating"].value_counts()

Everyone           8382
Teen               1146
Mature 17+          447
Everyone 10+        377
Adults only 18+       3
Unrated               2
Name: Content Rating, dtype: int64

In [58]:
df.head(5)

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,1,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,1,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,1,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,1,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [59]:
df.dtypes

Category            int32
Rating            float64
Reviews             int32
Size               object
Installs            int32
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

# Type feature

In [60]:
df["Type"].value_counts()

Free    9591
Paid     765
Name: Type, dtype: int64

In [61]:
#create dummy variable for the Type feature
dummies = pd.get_dummies(df["Type"])

In [62]:
dummies

       Free  Paid
0         1     0
1         1     0
2         1     0
3         1     0
4         1     0
...     ...   ...
10836     1     0
10837     1     0
10838     1     0
10839     1     0
10840     1     0

[10357 rows x 2 columns]

In [63]:
#marge df with the dummy dataframe
df = pd.concat([df,dummies],axis="columns")

In [64]:
#Drop Type from dataframe
df.drop("Type",axis="columns",inplace=True)

In [65]:
df["Content Rating"].value_counts()

Everyone           8382
Teen               1146
Mature 17+          447
Everyone 10+        377
Adults only 18+       3
Unrated               2
Name: Content Rating, dtype: int64

# Content Rating Feature

In [66]:
#create dummy variable for the "Content Rating" feature
dummies = pd.get_dummies(df["Content Rating"])
dummies

       Adults only 18+  Everyone  Everyone 10+  Mature 17+  Teen  Unrated
0                    0         1             0           0     0        0
1                    0         1             0           0     0        0
2                    0         1             0           0     0        0
3                    0         0             0           0     1        0
4                    0         1             0           0     0        0
...                ...       ...           ...         ...   ...      ...
10836                0         1             0           0     0        0
10837                0         1             0           0     0        0
10838                0         1             0           0     0        0
10839                0         0             0           1     0        0
10840                0         1             0           0     0        0

[10357 rows x 6 columns]

In [67]:
#marge df with the dummy dataframe
df = pd.concat([df,dummies],axis="columns")

In [68]:
#Drop Type from dataframe
df.drop("Content Rating",axis="columns",inplace=True)

In [69]:
df.dtypes

Category             int32
Rating             float64
Reviews              int32
Size                object
Installs             int32
Price              float64
Genres              object
Last Updated        object
Current Ver         object
Android Ver         object
Free                 uint8
Paid                 uint8
Adults only 18+      uint8
Everyone             uint8
Everyone 10+         uint8
Mature 17+           uint8
Teen                 uint8
Unrated              uint8
dtype: object

# Genres Feature

In [71]:
df

,Category,Rating,Reviews,Size,Installs,Price,Genres,Last Updated,Current Ver,Android Ver,Free,Paid,Adults only 18+,Everyone,Everyone 10+,Mature 17+,Teen,Unrated
0,1,4.100000,159,19M,10000,0.0,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,1,0,0,1,0,0,0,0
1,1,3.900000,967,14M,500000,0.0,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,1,0,0,1,0,0,0,0
2,1,4.700000,87510,8.7M,5000000,0.0,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,1,0,0,1,0,0,0,0
3,1,4.500000,215644,25M,50000000,0.0,Art & Design,"June 8, 2018",Varies with device,4.2 and up,1,0,0,0,0,0,1,0
4,1,4.300000,967,2.8M,100000,0.0,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,12,4.500000,38,53M,5000,0.0,Education,"July 25, 2017",1.48,4.1 and up,1,0,0,1,0,0,0,0
10837,12,5.000000,4,3.6M,100,0.0,Education,"July 6, 2018",1.0,4.1 and up,1,0,0,1,0,0,0,0
10838,21,4.189542,3,9.5M,1000,0.0,Medical,"January 20, 2017",1.0,2.2 and up,1,0,0,1,0,0,0,0
10839,4,4.500000,114,Varies with device,1000,0.0,Books & Reference,"January 19, 2015",Varies with device,Varies with device,1,0,0,0,0,1,0,0
10840,19,4.500000,398307,19M,10000000,0.0,Lifestyle,"July 25, 2018",Varies with device,Varies with device,1,0,0,1,0,0,0,0

In [70]:
df["Genres"].value_counts()

Tools                                842
Entertainment                        588
Education                            527
Business                             427
Medical                              408
                                    ...
Parenting;Brain Games                  1
Travel & Local;Action & Adventure      1
Lifestyle;Pretend Play                 1
Tools;Education                        1
Strategy;Creativity                    1
Name: Genres, Length: 119, dtype: int64

In [73]:
df["Genres"] = lb.fit_transform(df["Genres"])

In [75]:
sorted(df["Genres"].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118]

In [76]:
df

,Category,Rating,Reviews,Size,Installs,Price,Genres,Last Updated,Current Ver,Android Ver,Free,Paid,Adults only 18+,Everyone,Everyone 10+,Mature 17+,Teen,Unrated
0,1,4.100000,159,19M,10000,0.0,9,"January 7, 2018",1.0.0,4.0.3 and up,1,0,0,1,0,0,0,0
1,1,3.900000,967,14M,500000,0.0,12,"January 15, 2018",2.0.0,4.0.3 and up,1,0,0,1,0,0,0,0
2,1,4.700000,87510,8.7M,5000000,0.0,9,"August 1, 2018",1.2.4,4.0.3 and up,1,0,0,1,0,0,0,0
3,1,4.500000,215644,25M,50000000,0.0,9,"June 8, 2018",Varies with device,4.2 and up,1,0,0,0,0,0,1,0
4,1,4.300000,967,2.8M,100000,0.0,11,"June 20, 2018",1.1,4.4 and up,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,12,4.500000,38,53M,5000,0.0,39,"July 25, 2017",1.48,4.1 and up,1,0,0,1,0,0,0,0
10837,12,5.000000,4,3.6M,100,0.0,39,"July 6, 2018",1.0,4.1 and up,1,0,0,1,0,0,0,0
10838,21,4.189542,3,9.5M,1000,0.0,71,"January 20, 2017",1.0,2.2 and up,1,0,0,1,0,0,0,0
10839,4,4.500000,114,Varies with device,1000,0.0,19,"January 19, 2015",Varies with device,Varies with device,1,0,0,0,0,1,0,0
10840,19,4.500000,398307,19M,10000000,0.0,67,"July 25, 2018",Varies with device,Varies with device,1,0,0,1,0,0,0,0

In [77]:
df.dtypes

Category             int32
Rating             float64
Reviews              int32
Size                object
Installs             int32
Price              float64
Genres               int32
Last Updated        object
Current Ver         object
Android Ver         object
Free                 uint8
Paid                 uint8
Adults only 18+      uint8
Everyone             uint8
Everyone 10+         uint8
Mature 17+           uint8
Teen                 uint8
Unrated              uint8
dtype: object

In [96]:
val = df["Android Ver"].unique()

In [98]:
val2=list(val)

In [99]:
val2

['4.0.3 and up',
 '4.2 and up',
 '4.4 and up',
 '2.3 and up',
 '3.0 and up',
 '4.1 and up',
 '4.0 and up',
 '2.3.3 and up',
 'Varies with device',
 '2.2 and up',
 '5.0 and up',
 '6.0 and up',
 '1.6 and up',
 '1.5 and up',
 '2.1 and up',
 '7.0 and up',
 '5.1 and up',
 '4.3 and up',
 '4.0.3 - 7.1.1',
 '2.0 and up',
 '3.2 and up',
 '4.4W and up',
 '7.1 and up',
 '7.0 - 7.1.1',
 '8.0 and up',
 '5.0 - 8.0',
 '3.1 and up',
 '2.0.1 and up',
 '4.1 - 7.1.1',
 nan,
 '5.0 - 6.0',
 '1.0 and up',
 '2.2 - 7.1.1',
 '5.0 - 7.1.1']

In [101]:
df.isna().sum()

Category           0
Rating             0
Reviews            0
Size               0
Installs           0
Price              0
Genres             0
Last Updated       0
Current Ver        8
Android Ver        2
Free               0
Paid               0
Adults only 18+    0
Everyone           0
Everyone 10+       0
Mature 17+         0
Teen               0
Unrated            0
dtype: int64